max_generations: 3
similarity_weight: 0.8
length_weight: 0.2
max_no_improve: 2
leakage_similarity_threshold: 0.45
leakage_ngram_size: 3
leakage_ngram_overlap_threshold: 0.1
min_prompt_tokens: 2
max_prompt_tokens: 200
max_prompt_increase_ratio: 2.0
max_prompt_increase_tokens: 40
min_improvement_attempts: 2
llm_execution:
  mode: lmstudio  # or: openai_compatible, echo, local
  api_url: http://127.0.0.1:1234
  timeout_seconds: 30
  # Model name should be specified when calling run_pipeline()
llm_improvement:
  mode: lmstudio
  api_url: http://127.0.0.1:1234
  timeout_seconds: 30
llm_evaluation:
  mode: lmstudio
  api_url: http://127.0.0.1:1234
  timeout_seconds: 30
